#!/bin/sh

# Cores
NC='\033[0m' # No Color
Blue='\033[1;34m'
Red='\033[1;31m'

# Rodar o phpstan
echo -e "${Blue}1. Rodando o PHPStan${NC}"
./vendor/bin/phpstan
if [ $? -ne 0 ]; then
  echo -e "${Red} O PHPStan encontrou erros. ${NC}"
  exit 1
fi

# Rodar os teste
echo -e "${Blue}2. Rodando o Testes em paralelo${NC}"
php artisan test --parallel
if [ $? -ne 0 ]; then
  echo -e "${Red} Tivemos erro em algum teste, revise o código ou o teste! ${NC}"
  exit 1
fi

# Formatar cada arquivo alterado usando o Laravel Pint
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

echo -e "${Blue}3. Formatando os arquivos com o Laravel Pint${NC}"

for FILE in $STAGED_FILES
do
  ./vendor/bin/pint "${FILE}"
  git add "${FILE}"
done

exit 0